<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Application Form</title>

    <!-- Favicon -->
    <link rel="icon" href="{{ asset('assets/images/favicon_2.png') }}" sizes="32x32" type="image/png">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">

    <!-- Stylesheets -->
    <link rel="stylesheet" href="{{ asset('assets/css/common.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/buttons.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/apply_form.css') }}">

</head>

<body class="pt-md-0 pt-5">
    
    <div class="d-sm-none d-block mt-5 text-light">.</div>
    <div class="d-sm-none d-block mt-5 text-light">.</div>
    <div class="d-sm-none d-block mt-5 text-light">.</div>
    <div class="main">
        <div class="container px-0 m-0 w-100 d-flex justify-content-center align-items-center">
            <div class="row logoimg mb-3 ">
                <img src="{{ asset('assets/images/logo.png') }}" height="100%" alt="">
            </div>
        </div>
        @if(session('status'))
            <div class="alert alert-{{ session('status') }}">
                {{ session('message') }}
            </div>
        @endif
        
        <div class="container-fluid ">

            <form action="{{ route('job_app_store') }}" method="POST" enctype="multipart/form-data">
                @csrf
            <div class="maindiv">
                <div class="row">
                    <p>{{$list->job_title}}</p>
                    <!-- Basic Details -->
                    {{-- <div class="col-sm-12 col-md-4 col-xl-3 mb-3">
                        <label for="code">Code <span>*</span></label>
                        <input type="text" class="form-control" name="code" id="code" placeholder="(Autogenerated)"
                            readonly >
                    </div> --}}
                    <div class="col-sm-12 col-md-4 col-xl-3 mb-3">
                            <label for="code">Job Location<span>*</span></label>
                            <select name="location" id="" class="form-select" required>
                                <option value="" selected disabled>Select location</option>
                                @foreach ($location as $loc)
                                    <option value="{{ $loc->store_geo }}">{{ $loc->store_geo }}</option>
                                @endforeach
                            </select>
                        </div>
                    <div class="col-sm-12 col-md-4 col-xl-3 mb-3">
                        <input  hidden type="text" name="job_id" value="{{ $list->id }}">
                        <label for="name">Full Name <span>*</span></label>
                        <input type="text" class="form-control" name="name" id="name" placeholder="Enter Your Full Name" value="{{ old('name') }}"
                            >
                            @if ($errors->has('name'))
                            <div class="text-danger">{{ $errors->first('name') }}</div>
                        @enderror
                    </div>
                    <div class="col-sm-12 col-md-4 col-xl-3 mb-3">
                        <label for="dob">Date Of Birth <span>*</span></label>
                        <input type="date" class="form-control" name="dob" id="dob" value="{{ old('dob') }}" >
                        @if ($errors->has('dob'))
                        <div class="text-danger">{{ $errors->first('dob') }}</div>
                        @enderror
                    </div>
                    <div class="col-sm-12 col-md-4 col-xl-3 mb-3">
                        <label for="email">Email ID <span>*</span></label>
                        <input type="email" class="form-control" name="email" id="email" value="{{ old('email') }}"
                            placeholder="Enter Your Email ID" >
                        @if ($errors->has('email'))
                        <div class="text-danger">{{ $errors->first('email') }}</div>
                        @enderror
                    </div>
                    <div class="col-sm-12 col-md-4 col-xl-3 mb-3">
                        <label for="contactno">Contact Number <span>*</span></label>
                        <input type="number" class="form-control" name="contactno" id="contactno"
                            oninput="validate_contact(this)" min="6000000000" max="9999999999"
                            placeholder="Enter Your Contact Number"  value="{{ old('contactno') }}">
                            @if ($errors->has('contactno'))
                            <div class="text-danger">{{ $errors->first('contactno') }}</div>
                            @enderror
                    </div>
                    <div class="col-sm-12 col-md-4 col-xl-3 mb-3">
                        <label for="address">Address <span>*</span></label>
                        <textarea rows="1" class="form-control" name="address" id="address"
                            placeholder="Enter Your Address" value="{{ old('daddressob') }}" ></textarea>
                        @if ($errors->has('address'))
                        <div class="text-danger">{{ $errors->first('address') }}</div>
                        @enderror
                    </div>
                    <div class="col-sm-12 col-md-4 col-xl-3 mb-3">
                        <label for="city">City <span>*</span></label>
                        <input type="text" class="form-control" name="city" id="city" placeholder="Enter Your City" value="{{ old('city') }}"
                            >
                            @if ($errors->has('city'))
                            <div class="text-danger">{{ $errors->first('city') }}</div>
                            @enderror
                    </div>
                    <div class="col-sm-12 col-md-4 col-xl-3 mb-3">
                        <label for="state">State <span>*</span></label>
                        <input type="text" class="form-control" name="state" id="state" placeholder="Enter Your State" value="{{ old('state') }}"
                            >
                            @if ($errors->has('state'))
                            <div class="text-danger">{{ $errors->first('state') }}</div>
                            @enderror
                    </div>
                    <div class="col-sm-12 col-md-4 col-xl-3 mb-3">
                        <label for="pincode">Pincode <span>*</span></label>
                        <input type="number" class="form-control" name="pincode" id="pincode"
                            oninput="validate_pin(this)" min="000000" max="999999" placeholder="Enter Your Pincode" value="{{ old('pincode') }}"
                            >
                            @if ($errors->has('pincode'))
                            <div class="text-danger">{{ $errors->first('pincode') }}</div>
                            @enderror
                    </div>

                    <!-- Eudcational Details -->
                    <div class="col-sm-12 col-md-4 col-xl-3 mb-3">
                        <label for="edubkgrnd">Educational Background</label>
                        <textarea rows="1" class="form-control" name="edubkgrnd" id="edubkgrnd" value="{{ old('edubkgrnd') }}"
                            placeholder="Enter Your Educational Background"></textarea>
                            @if ($errors->has('edubkgrnd'))
                            <div class="text-danger">{{ $errors->first('edubkgrnd') }}</div>
                            @enderror
                    </div>
                    <div class="col-sm-12 col-md-4 col-xl-3 mb-3">
                        <label for="workexp">Work Experience</label>
                        <input type="text" class="form-control" name="workexp" id="workexp" value="{{ old('workexp') }}"
                            placeholder="Enter Your Work Experience">
                            @if ($errors->has('workexp'))
                            <div class="text-danger">{{ $errors->first('workexp') }}</div>
                            @enderror
                    </div>
                    <div class="col-sm-12 col-md-4 col-xl-3 mb-3">
                        <label for="skills">Skills</label>
                        <textarea rows="1" class="form-control" name="skills" id="skills" value="{{ old('skills') }}"
                            placeholder="Enter Your Skills"></textarea>
                            @if ($errors->has('skills'))
                            <div class="text-danger">{{ $errors->first('skills') }}</div>
                            @enderror
                    </div>
                    <div class="col-sm-12 col-md-4 col-xl-3 mb-3">
                        <label for="noticeperiod">Notice Period</label>
                        <input type="number" class="form-control" name="noticeperiod" id="noticeperiod" value="{{ old('noticeperiod') }}"
                            placeholder="Enter Notice Period">

                    </div>


                    <!-- Files -->
                    <div class="col-sm-12 col-md-4 col-xl-3 mb-3">
                        <label for="certifications">Certifications</label>
                        <input type="file" class="form-control" name="certifications" id="certifications">
                        @if ($errors->has('certifications'))
                            <div class="text-danger">{{ $errors->first('certifications') }}</div>
                            @enderror
                    </div>
                    <div class="col-sm-12 col-md-4 col-xl-3 mb-3">
                        <label for="resume">Upload Resume <span>*</span></label>
                        <input type="file" class="form-control" name="resume" id="resume" >
                        @if ($errors->has('resume'))
                            <div class="text-danger">{{ $errors->first('resume') }}</div>
                            @enderror
                    </div>

                    <div class="col-sm-12 col-md-12 col-xl-12 mt-3 d-flex justify-content-center align-items-center">
                        <button type="submit" id="submitBtn" class="applybtn">Save</button>
                    </div>

                </div>
            </div>
        </form>
        </div>
    </div>
    

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

</body>

<script>
    // function validate_contact(input) {
    //     const value = input.value;

    //     if (value.length > 10) {
    //         input.value = value.slice(0, 10);
    //     }
    // }
    // function validate_pin(input) {
    //     const value = input.value;

    //     if (value.length > 6) {
    //         input.value = value.slice(0, 6);
    //     }
    // }
</script>

</html>